version: 1

loggers:
  root:
    level: DEBUG
    handlers: [console]
  tornado:
    level: DEBUG
    handlers: [console,log]
    propagate: no
  tornado.access:
    level: DEBUG
    handlers: [console, access]
    propagate: no
  log:
    level: DEBUG
    handlers: [console,log]
    propagate: no

formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
  access:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    filename: 'log/access.log'
    maxBytes: 100000000
    backupCount: 100
    formatter: simple
  log:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    filename: 'log/log.log'
    maxBytes: 100000000
    backupCount: 100
    formatter: simple
